name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: CMake
      run: docker run --rm -v "$GITHUB_WORKSPACE":/usr/src/app -w /usr/src/app/docker-build 2bitxor/my-gcc:0.0.1 cmake -D ENABLE_COVERAGE:BOOL=TRUE ..
    - name: Make
      run: docker run --rm -v "$GITHUB_WORKSPACE":/usr/src/app -w /usr/src/app/docker-build 2bitxor/my-gcc:0.0.1 make
    - name: CTest
      run: docker run --rm -v "$GITHUB_WORKSPACE":/usr/src/app -w /usr/src/app/docker-build 2bitxor/my-gcc:0.0.1 ctest -V
